---
title: 'Week 02: In-class R coding practice'
author: "JT Larkin"
date: "9/9/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#Iris Dataset

data(iris)

head(iris)

iris$Sepal.Width



#Mean and Standard Deviation

mean(iris$Sepal.Length)

sd(iris$Sepal.Width)



#Scatterplot

plot(x = iris$Sepal.Width, y = iris$Sepal.Length)


data_center_x = mean(iris$Sepal.Width)
data_center_y = mean(iris$Sepal.Length)
c(data_center_x, data_center_y)


#Add point to plot

plot(x = iris$Sepal.Width, y = iris$Sepal.Length)
points(x = data_center_x, y = data_center_y, col = "red")



#Draw line

line_point_slope = function(x, x1, y1, slope)
{
  get_y_intercept = 
    function(x1, y1, slope) 
      return(-(x1 * slope) + y1)
  
  linear = 
    function(x, yint, slope) 
      return(yint + x * slope)
  
  return(linear(x, get_y_intercept(x1, y1, slope), slope))
}



line_point_slope(2, 4, 4, -2)




#Add curve to plot

plot(x = iris$Sepal.Width, y = iris$Sepal.Length, 
     main="Iris Plot", xlab= "Sepal Length", ylab= "Sepal Width",
     col="blue")
points(x = data_center_x, y = data_center_y, col = "red")
curve(
  line_point_slope(
    x, 
    data_center_x, 
    data_center_y,
    -0.1), 
  add = TRUE)



```

1.) How far did your group get?
2.) What parts of the exercise were difficult, or too easy?
3.) Upload at least one figure or screenshot from work and explain


```{r}
#Other Datasets


library(MASS)
data(Animals)
head(Animals)
```

